ahmadawais/hacktoberfest

README.md

Added the event details in my own words.

ADD event details

---

README.md
resources.md

Added resources for basic Git learning as well as Version Control for WordPress.

Add Git resources

---

README.md

Add feedback about the meetup

---

resources.md

This PR IMPROVES: Markdown Syntax and Fix #10 as per our discussion in the meetup.

IMPROVE: Markdown Syntax and Fix #10

---

resources.md

Some Gui Clients added

---

resources.md

Added the Vogella Git tutorial to resources.md
Addresses issue #3

Added Vogella Git Tutorial to Resources.md

---

README.md

Merged the opinion and feedback section.

IMPROVE: Add Proper Formatting to Feedback Section

---

README.md

Some typo mistakes removed by a friend

REMOVE typo mistakes 

---

README.md

In this pull request, I added that what I learned from the meetup. Before this meet-up I don't know about the mark down syntax to write the document. After attending it I come to know about this.

Update: new thing I learned in this event

---

README.md

Merge Git Resources

---

README.md

This PR Rearranges README.md to be consistent.

Rearrange README.md

---

README.md

ADD: Feedback about the meetup

---

README.md

Added the feedback about the event. Minor grammar fixes.

ADD Feedback

---

README.md

I added a semi-colon to a heading.

Add semi-colon to a sub-heading

---

README.md

ADD Git Tutorials

---

README.md

ADD Learn Version Control with Git

Learn Version Control with Git

---

README.md

TitleCase a Sub-Heading

---

README.md

I added a question mark to a sub-heading.

Add question mark to a sub-heading.

---

README.md

Pro Git is pretty awesome. Add it.

Add Pro Git

---

README.md

ADD The Git Community Book

---

README.md

ADD Git Pocket Guide

---

README.md

ADD Git Real: Code School

---

README.md

Add new tools for GitHub

---

README.md

Proposed new Git tools

---

README.md

ADD Git Branching Guide

---

README.md

Improved formatting

---

README.md

Add Git Magic

---

README.md

Add Git from the bottom up

---

README.md

Add Git Howto

---

README.md

Migrating to Git LFS

---

README.md

ADD: source tree website
@ahmadawais

Add Source Tree to git tools

---

README.md

ADD GitHub Desktop

---

README.md

IMPROVE Tools Description

---

README.md

Add Three Git Tools

---

README.md

Add a couple of handy extensions for Git

Add Two Git Extensions

---

README.md

Add a Git extension and improve the description

Add Git Extension

---

README.md

Fix emoji in How to Contribute section, add do not emoji
Improve extensions section, provide lightning emoji

Change do not emoji in How to Contribute README.md

---

LICENSE

ADD MIT LICENSE

---

README.md

ADD New resources to Git Basics and Git for WordPress.

ADD New Resources

---

README.md

ADD GitExtensions, GitUp, GitKraken

ADD Resources

---

README.md

ADD Repository Hosting Heading

ADD Repository Hosting Heading

---

README.md

Add BitBucket

---

README.md

ADD CodePlex

---

README.md

ADD GitLab 
* [GitLab.com](https://about.gitlab.com/gitlab-com/) - a free Git repository hosting service served by GitLab EE. Unlimited repositories and private collaborators

ADD GitLab

---

README.md

* [AWS CodeCommit](https://aws.amazon.com/codecommit/) - a SaaS service provided by Amazon Web Service on high availability infrastructure

ADD AWS CodeCommit

---

README.md

* [Gitolite](http://gitolite.com/gitolite/) - a simple with fine-grained access control
* [GitHub Enterprise](https://enterprise.github.com/) - self-hosted solution provided from GitHub
* [Bitbucket Server](https://www.atlassian.com/software/bitbucket/server) - self-hosted refrom Atlassian. Good integration with JIRA and other Atlassian products
* [GitLab CE/EE](https://gitlab.com/) - a popular open-source Git (CE) with paid support option (EE).
* [Upsource](https://www.jetbrains.com/upsource) - recent offer from Jetbrains, a famos developer-oriented software company. Code repository hosting feature pending. Free for 10 users. Good integration with YouTrack and TeamCity
* [GitBucket](https://github.com/takezoe/gitbucket/) - a GitHub clone powered by Scala.
* [Gogs](http://gogs.io/) - a …

ADD Self Hosted Git Resources

---

README.md

*Inexpensive branching allows people adopt workflows other than the classic centralilzed workflow*
* [Pro Git - Distributed Workflows](https://git-scm.com/book/it/v2/Distributed-Git-Distributed-Workflows)
* [Atlassian Git Tutorial - Comparing Workflows](https://www.atlassian.com/git/tutorials/comparing-workflows)
* [Gitflow](http://nvie.com/posts/a-successful-git-branching-model/) - the most well-known Git workflow model
* [GitHub flow](http://scottchacon.com/2011/08/31/github-flow.html) - a simple branching model with a single master
* [GitLab flow](https://about.gitlab.com/2014/09/29/gitlab-flow/)
* [Git DMZ Flow](https://gist.github.com/djspiewak/9f2f91085607a4859a66)

ADD Workflow

---

README.md

*Git provide hooks at commit/push phrase, allowing integration with and code quality checking tool and Continuous Integration (CI)*
* [pre-commit](http://pre-commit.com/) - a framework for managing and maintaining multi-language pre-commit hooks from Yelp. Extensive support for multiple programming language.
* [Overcommit](https://github.com/brigade/overcommit/) - a extendable Git hook manager written with Ruby.
* [git-hooks](https://github.com/icefox/git-hooks/) - tool to manage project, user, and global Git hooks
* [quickhook](https://github.com/dirk/quickhook/) - a fast, Unix'y, opinionated Git hook runner

ADD Git Hook management

---

README.md

FIX Consistency in Markdown

---

README.md

ADD git and gitflow cheat-sheet

ADD git and gitflow cheat-sheet

---

README.md

> A curated list of GitHub's awesomeness
The awesomeness is currently organized into just a few different buckets: 
* [Infomation for people who are new to GitHub](#infomation-for-people-who-are-new-to-github)
* [Resources for those already familiar with GitHub](#resources-for-those-already-familiar-with-github)
* [Tips, tricks, tools, and add-ons for GitHub power users](#tips-tricks-tools-and-add-ons-for-github-power-users)
* [Novel uses of GitHub](#novel-uses-of-github)
---
- [Code School's Try Git](https://try.github.io/levels/1/challenges/1) - If you'd like to better understand Git, one of the technologys that makes GitHub possible, this is a great place to start. No GitHub account required.
- [Git-it](https://github.com/jlord/git-it) -- :computer: :mortar_board: A workshopper for …

ADD GitHub Resources

---

README.md

TitleCaseIt

---

README.md

> Collection of `git-tips`, want to add your tips? Checkout [contributing.md](./contributing.md)
* [git-tip](https://www.npmjs.com/package/git-tip) - A handy CLI to make optimum use of these tips. ([Here in Docker container](https://github.com/djoudi5/docker-git-tip))
P.S: All these commands are tested on `git version 2.7.4 (Apple Git-66)`.
* [Everyday Git in twenty commands or so](#everyday-git-in-twenty-commands-or-so)
* [Show helpful guides that come with Git](#show-helpful-guides-that-come-with-git)
* [Search change by content](#search-change-by-content)
* [Sync with remote, overwrite local changes](#sync-with-remote-overwrite-local-changes)
* [List of all files till a commit](#list-of-all-files-till-a-commit)
* [Git reset first commit](#git-reset-first-commit)
* [List all the …

ADD Git Tips

---

README.md

⚡️ ADD More Emoji

---

README.md

Add a colon at the end of heading to improve consistency in the readme.
What does this Pull Request do?
IMPROVE

ADD: Colon at the end of the heading

---

README.md

[How to Create a Pull Request](https://services.github.com/on-demand/intro-to-github/create-pull-request) — learn to create a GitHub Pull Request

📦 NEW: How to PR

---

README.md

Add git branching tutorial to README.md

---

README.md

This PR includes...
* Slight improvement to grammar
* Using of `"` quotation symbol instead of the unicode version to avoid issues when being copy-pasted into the terminal and used by beginners.

👌 IMPROVE: Improve grammar and examples

---

README.md

ADD: Period at the end of a sentence

---

README.md

Add details about what Hacktoberfest is.

NEW: Add details about Hacktoberfest

---

README.md

📦 NEW: Add cross-platform Git Client
Linked to a new cross-platform Git Client, from the makers of the popular Sublime Merge editor.

📖 DOC: Add a Git client to the Git Tools section.

---

README.md

Updated Readme - Added Git Tutorial

---

README.md

NEW Tig text-mode interface for Git

Add Tig text-mode interface for Git

---

README.md

NEW git-standup to recall what you did on the last working day

Add git-standup

---

README.md

NEW - Added 'no fast-forward' `--no-ff` flag to `git merge` on the cheat sheet

Added `git merge --no-ff` to the git commands

---

README.md

IMPROVE: Update links to https and update some redirected URLs

Links direct to https

---

README.md

Remove duplicate listing of GitKraken in GIT Tools list.
What does this Pull Request do?
FIX

🐛 FIX: Remove duplicate listing of GitKraken in GIT Tools list

---

README.md

Improve: Update README.md
New: Added 3 tutorials links from Udacity to learn about Git & GitHub

NEW: Add Git & GitHub tutorials

---

README.md

IMPROVE: add the link to powerful browser extension

Update readme. Added github tool

---

README.md

:book: Add GitLens vscode extension to list of Git Extensions.

📖 Add GitLens to list of extensions

---

README.md

Add Git Tutotial

---

README.md

NEW guide in 10 simple steps for the people who are beginners and want to contribute to any GitHub repository.

How to contribute to an open source library on GitHub

---

README.md

Added 8 ways to sync Git with WordPress.

👌 UPDATE: README.md

---

README.md

An informative and fancy bash prompt for Git users.

📦 NEW: Bash Prompt Tool for Git

---

README.md

📦 NEW: Git Hooks for Node.js

---

README.md

GitHub learning paths

---

README.md

Adding link to Github tutorial 'Learn enough Git to be Dangerous' and adding command for undoing last commit in Git Tips section.

📦 NEW: link to Github tutorial + Git Tips section

---

README.md

Add a link to SourceForge in the Git hosts sections.
I know it's isn't well known and is a bit old but it doesn't hurt including it.

📦 NEW: Add SourceForge as a Git host

---

README.md

https://blog.prototypr.io/fun-with-git-8385da9c748c]

Added a resource for people new to github

---

README.md

Show git log with beautiful graph tree (adog)
IMPROVE

Show git log with beautiful graph tree (adog)

---

README.md

📦 NEW: DO Config

---

README.md

 📖 DOC: Ansible Cloud Modules

---

README.md

 📖 DOC: DigitalOcean in Action

---

README.md

 📖 DOC: DigitalOcean Developer documentation

---

README.md

 📖 DOC: GitHub Guide

---

README.md

Add Git Awesome Browser Extensions

📖 DOC: Add Git Awesome Browser Extensions

---

README.md

Add Git Cheat Sheet and Git Flow

📖 DOC: Add Git Cheat Sheet and Git Flow

---

README.md

📖 DOC: Add GitHub Cheat Sheet

---

README.md

🐛 FIX: headings

---

README.md

📦 NEW: DigitalOcean Open Source

---

README.md

📖 DOC: Add Git Add-ons

---

README.md

📦 NEW: Community OSS projects

---

README.md

📦 NEW:  drophosts

---

README.md

📦 NEW: droplan

---

README.md

📖 DOC: Add Sublime Text Editor

---

README.md

📖 DOC: Add Vim Code Editor

---

README.md

📦 NEW: foreman-digitalocean

---

README.md

📦 NEW: lita-digitalocean

---

README.md

📦 NEW: hostpool

---

README.md

📦 NEW: ddns

---

README.md

📦 NEW: OSS resources

---

README.md

📦 NEW: Clients

---

README.md

📦 NEW:  digitalocean-indicator

---

README.md

📦 NEW: domanager

---

README.md

📦 NEW: OceanBar

---

README.md

📦 NEW: Tugboat

---

README.md

📦 NEW:  vid tuts

---

README.md

📦 NEW: DO Community

---

README.md

👌 IMPROVE: layout

---

README.md

📦 NEW: squash

---

README.md

📦 NEW: summary

---

README.md

📦 NEW: line-summary

---

README.md

📦 NEW: effort

---

README.md

📦 NEW: authors

---

README.md

📦 NEW: changelog

---

README.md

📦 NEW: commits-since

---

README.md

📦 NEW:  count

---

README.md

📦 NEW: create-branch

---

README.md

📦 NEW: delete-branch

---

README.md

📦 NEW: delete-submodule

---

README.md

📦 NEW: delete-tag

---

README.md

📦 NEW: delete-merged-branches

---

README.md

📦 NEW: fresh-branch

---

README.md

📦 NEW: guilt

---

README.md

📦 NEW: merge-into

---

README.md

📦 NEW: graft

---

README.md

📦 NEW: alias

---

README.md

📦 NEW: git ignore

---

README.md

📦 NEW: info

---

README.md

📦 NEW: fork

---

README.md

📦 NEW: release

---

README.md

📦 NEW: contrib

---

README.md

📦 NEW:  repl

---

README.md

📦 NEW: undo

---

README.md

📦 NEW: gh-pages

---

README.md

📦 NEW: scp

---

README.md

📦 NEW: setup

---

README.md

📦 NEW: touch

---

README.md

📦 NEW: feature|refactor|bug|chore

---

README.md

📦 NEW: local-commits

---

README.md

📦 NEW: archive-file

---

README.md

📦 NEW: missing

---

README.md

📦 NEW: lock

---

README.md

📦 NEW:  locked

---

README.md

📦 NEW: unlock

---

README.md

📦 NEW: reset-file

---

README.md

📦 NEW: root

---

README.md

📦 NEW: delta

---

README.md

📦 NEW: merge-repo

---

README.md

📦 NEW: psykorebase

---

README.md

📦 NEW: gitflow

---

README.md

📦 NEW: feature

---

README.md

📦 NEW: hotfix

---

README.md

📦 NEW: support

---

README.md

📦 NEW: git up

---

README.md

📦 NEW: hub

---

README.md

📦 NEW: remote add

---

README.md

📦 NEW: fetch

---

README.md

📦 NEW: cherry-pick

---

README.md

📦 NEW: more from hub

---

README.md

📦 NEW: In-depth guide about hacktoberfest

---

README.md

📦 NEW: Dev.to

---

README.md

📦 NEW: 2020

---

README.md

Add getting started Git tutorial from pluralsight

---

README.md

Add GitHub tutorial LinkedIn

---

README.md

Intro to Git by DataCamp

---

README.md

Become an Expert in Git & GitHub in 4 Hours
